export enum AT {
    ADD_APP = 'ADD_APP',
    
    USER_LOGIN = 'USER_LOGIN',
    USER_LOGOUT = 'USER_LOGOUT',

    FETCH_PROFILE = 'FETCH_PROFILE',
    FETCH_PROFILE_FULFILLED = 'FETCH_PROFILE_FULFILLED'
}

export default AT